// <auto-generated />
using System;
using AlgoApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlgoApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200428075747_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("AlgoApp.Data.Bookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("AlgoApp.Data.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "绪论",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "线性表",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "栈和队列",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "串",
                            Order = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "数组和广义表",
                            Order = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "树和二叉树",
                            Order = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "图",
                            Order = 7
                        },
                        new
                        {
                            Id = 8,
                            Name = "动态存储管理",
                            Order = 8
                        },
                        new
                        {
                            Id = 9,
                            Name = "查找",
                            Order = 9
                        },
                        new
                        {
                            Id = 10,
                            Name = "内部排序",
                            Order = 10
                        },
                        new
                        {
                            Id = 11,
                            Name = "外部排序",
                            Order = 11
                        });
                });

            modelBuilder.Entity("AlgoApp.Data.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassName = "赵老师的班级_计科",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 2,
                            ClassName = "赵老师的班级_电信",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClassName = "钱老师的班级",
                            TeacherId = 3
                        });
                });

            modelBuilder.Entity("AlgoApp.Data.DailyPoints", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DailyPoints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2020, 4, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Points = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2020, 4, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Points = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2020, 4, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Points = 4,
                            UserId = 6
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2020, 4, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Points = 8,
                            UserId = 7
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2020, 4, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Points = 16,
                            UserId = 8
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2020, 4, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Points = 32,
                            UserId = 9
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2020, 4, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Points = 64,
                            UserId = 10
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2020, 4, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Points = 128,
                            UserId = 11
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2020, 4, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Points = 256,
                            UserId = 12
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2020, 4, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Points = 512,
                            UserId = 13
                        });
                });

            modelBuilder.Entity("AlgoApp.Data.DailyPractice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DailyPractices");
                });

            modelBuilder.Entity("AlgoApp.Data.FillingAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("FillingAnswers");
                });

            modelBuilder.Entity("AlgoApp.Data.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Read")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("AlgoApp.Data.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Analysis")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Analysis = "无",
                            ChapterId = 1,
                            Content = "算法的时间复杂度是指（）。",
                            Difficulty = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Analysis = "无",
                            ChapterId = 1,
                            Content = "算法的空间复杂度是指（）。",
                            Difficulty = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Analysis = "无",
                            ChapterId = 1,
                            Content = "以下哪个不是算法的重要特性（）。",
                            Difficulty = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Analysis = "无",
                            ChapterId = 2,
                            Content = "关于线性表的顺序存储结构和链式存储结构的描述中，正确的是（）。",
                            Difficulty = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Analysis = "无",
                            ChapterId = 2,
                            Content = "关于线性表说法正确的是（）。",
                            Difficulty = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Analysis = "无",
                            ChapterId = 2,
                            Content = "下面关于线性表的叙述中，错误的有（ ）",
                            Difficulty = 0,
                            Type = 1
                        });
                });

            modelBuilder.Entity("AlgoApp.Data.ResultTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Input")
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("ResultTests");
                });

            modelBuilder.Entity("AlgoApp.Data.SelectionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Correct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("SelectionOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "开发算法所花费的时间",
                            Correct = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "学习算法所需要的时间",
                            Correct = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "程序执行所需时间",
                            Correct = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "以上都不对",
                            Correct = true,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "算法代码的大小",
                            Correct = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 6,
                            Content = "算法所能处理数据的大小",
                            Correct = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 7,
                            Content = "程序执行所需内存大小",
                            Correct = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 8,
                            Content = "以上都不对",
                            Correct = true,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 9,
                            Content = "有穷性",
                            Correct = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 10,
                            Content = "确定性",
                            Correct = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 11,
                            Content = "可行性",
                            Correct = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 12,
                            Content = "易用性",
                            Correct = true,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 13,
                            Content = "线性表的顺序存储结构优于其链式存储结构",
                            Correct = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 14,
                            Content = "链式存储结构比顺序存储结构更能方便的表示各种逻辑结构",
                            Correct = true,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 15,
                            Content = "如频繁使用插入和删除结点操作，顺序存储结构更优于链式存储结构",
                            Correct = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 16,
                            Content = "顺序存储结构和链式存储结构都可以进行顺序存取",
                            Correct = true,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 17,
                            Content = "顺序存储方式只能用于存储线性结构",
                            Correct = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 18,
                            Content = "链表需要分配较大的连续空间，插入和删除不需要移动元素",
                            Correct = true,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 19,
                            Content = "在一个长度为n的有序单链表中插入一个新节点并仍保持有序的时间复杂度为O(n)",
                            Correct = true,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 20,
                            Content = "若用单链表来表示队列，则应该选用带尾指针的循环链表",
                            Correct = true,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 21,
                            Content = "线性表采用顺序存储，必须占用一片连续的存储单元。",
                            Correct = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 22,
                            Content = "线性表采用顺序存储，便于进行插入和删除操作。",
                            Correct = true,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 23,
                            Content = "线性表采用链接存储，必须占用一片连续的存储单元。",
                            Correct = true,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 24,
                            Content = "线性表采用链接存储，便于进行插入和删除操作。",
                            Correct = false,
                            QuestionId = 6
                        });
                });

            modelBuilder.Entity("AlgoApp.Data.StudentToClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentsToClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassroomId = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 2,
                            ClassroomId = 1,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 3,
                            ClassroomId = 1,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 4,
                            ClassroomId = 1,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 5,
                            ClassroomId = 1,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 6,
                            ClassroomId = 1,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 7,
                            ClassroomId = 1,
                            StudentId = 10
                        },
                        new
                        {
                            Id = 8,
                            ClassroomId = 1,
                            StudentId = 11
                        },
                        new
                        {
                            Id = 9,
                            ClassroomId = 1,
                            StudentId = 12
                        },
                        new
                        {
                            Id = 10,
                            ClassroomId = 1,
                            StudentId = 13
                        },
                        new
                        {
                            Id = 11,
                            ClassroomId = 2,
                            StudentId = 14
                        },
                        new
                        {
                            Id = 12,
                            ClassroomId = 2,
                            StudentId = 15
                        },
                        new
                        {
                            Id = 13,
                            ClassroomId = 2,
                            StudentId = 16
                        },
                        new
                        {
                            Id = 14,
                            ClassroomId = 2,
                            StudentId = 17
                        });
                });

            modelBuilder.Entity("AlgoApp.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDay = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 0,
                            Nickname = "Root",
                            Password = "5A5008BE2706857BBCABB8379803EAEB321BB799",
                            Points = 0,
                            Role = 0,
                            Username = "root"
                        },
                        new
                        {
                            Id = 2,
                            BirthDay = new DateTime(2000, 4, 28, 15, 57, 47, 401, DateTimeKind.Local).AddTicks(675),
                            Gender = 1,
                            Nickname = "赵老师",
                            Password = "A288A447BECB60599F59804FCF69B7770A7F6BC8",
                            Points = 0,
                            Role = 1,
                            Username = "teacherzhao"
                        },
                        new
                        {
                            Id = 3,
                            BirthDay = new DateTime(2000, 4, 28, 15, 57, 47, 401, DateTimeKind.Local).AddTicks(9349),
                            Gender = 2,
                            Nickname = "钱老师",
                            Password = "A288A447BECB60599F59804FCF69B7770A7F6BC8",
                            Points = 0,
                            Role = 1,
                            Username = "teacherqian"
                        },
                        new
                        {
                            Id = 4,
                            BirthDay = new DateTime(2000, 4, 28, 15, 57, 47, 401, DateTimeKind.Local).AddTicks(9393),
                            Gender = 1,
                            Nickname = "孙同学",
                            Password = "A288A447BECB60599F59804FCF69B7770A7F6BC8",
                            Points = 2,
                            Role = 2,
                            Username = "studentsun"
                        },
                        new
                        {
                            Id = 5,
                            BirthDay = new DateTime(2000, 4, 28, 15, 57, 47, 401, DateTimeKind.Local).AddTicks(9900),
                            Gender = 2,
                            Nickname = "李同学",
                            Password = "A288A447BECB60599F59804FCF69B7770A7F6BC8",
                            Points = 4,
                            Role = 2,
                            Username = "studentli"
                        },
                        new
                        {
                            Id = 6,
                            BirthDay = new DateTime(2000, 4, 28, 15, 57, 47, 401, DateTimeKind.Local).AddTicks(9923),
                            Gender = 2,
                            Nickname = "周同学",
                            Password = "A288A447BECB60599F59804FCF69B7770A7F6BC8",
                            Points = 8,
                            Role = 2,
                            Username = "student06"
                        },
                        new
                        {
                            Id = 7,
                            BirthDay = new DateTime(2000, 4, 28, 15, 57, 47, 401, DateTimeKind.Local).AddTicks(9926),
                            Gender = 2,
                            Nickname = "吴同学",
                            Password = "A288A447BECB60599F59804FCF69B7770A7F6BC8",
                            Points = 16,
                            Role = 2,
                            Username = "student07"
                        },
                        new
                        {
                            Id = 8,
                            BirthDay = new DateTime(2000, 4, 28, 15, 57, 47, 401, DateTimeKind.Local).AddTicks(9928),
                            Gender = 2,
                            Nickname = "郑同学",
                            Password = "A288A447BECB60599F59804FCF69B7770A7F6BC8",
                            Points = 32,
                            Role = 2,
                            Username = "student08"
                        },
                        new
                        {
                            Id = 9,
                            BirthDay = new DateTime(2000, 4, 28, 15, 57, 47, 401, DateTimeKind.Local).AddTicks(9931),
                            Gender = 2,
                            Nickname = "王同学",
                            Password = "A288A447BECB60599F59804FCF69B7770A7F6BC8",
                            Points = 64,
                            Role = 2,
                            Username = "student09"
                        },
                        new
                        {
                            Id = 10,
                            BirthDay = new DateTime(2000, 4, 28, 15, 57, 47, 401, DateTimeKind.Local).AddTicks(9934),
                            Gender = 2,
                            Nickname = "冯同学",
                            Password = "A288A447BECB60599F59804FCF69B7770A7F6BC8",
                            Points = 128,
                            Role = 2,
                            Username = "student10"
                        },
                        new
                        {
                            Id = 11,
                            BirthDay = new DateTime(2000, 4, 28, 15, 57, 47, 401, DateTimeKind.Local).AddTicks(9937),
                            Gender = 2,
                            Nickname = "陈同学",
                            Password = "A288A447BECB60599F59804FCF69B7770A7F6BC8",
                            Points = 256,
                            Role = 2,
                            Username = "student11"
                        },
                        new
                        {
                            Id = 12,
                            BirthDay = new DateTime(2000, 4, 28, 15, 57, 47, 401, DateTimeKind.Local).AddTicks(9939),
                            Gender = 2,
                            Nickname = "褚同学",
                            Password = "A288A447BECB60599F59804FCF69B7770A7F6BC8",
                            Points = 512,
                            Role = 2,
                            Username = "student12"
                        },
                        new
                        {
                            Id = 13,
                            BirthDay = new DateTime(2000, 4, 28, 15, 57, 47, 401, DateTimeKind.Local).AddTicks(9942),
                            Gender = 2,
                            Nickname = "卫同学",
                            Password = "A288A447BECB60599F59804FCF69B7770A7F6BC8",
                            Points = 1024,
                            Role = 2,
                            Username = "student13"
                        },
                        new
                        {
                            Id = 14,
                            BirthDay = new DateTime(2000, 4, 28, 15, 57, 47, 401, DateTimeKind.Local).AddTicks(9945),
                            Gender = 2,
                            Nickname = "蒋同学",
                            Password = "A288A447BECB60599F59804FCF69B7770A7F6BC8",
                            Points = 0,
                            Role = 2,
                            Username = "student10"
                        },
                        new
                        {
                            Id = 15,
                            BirthDay = new DateTime(2000, 4, 28, 15, 57, 47, 401, DateTimeKind.Local).AddTicks(9947),
                            Gender = 2,
                            Nickname = "沈同学",
                            Password = "A288A447BECB60599F59804FCF69B7770A7F6BC8",
                            Points = 0,
                            Role = 2,
                            Username = "student11"
                        },
                        new
                        {
                            Id = 16,
                            BirthDay = new DateTime(2000, 4, 28, 15, 57, 47, 401, DateTimeKind.Local).AddTicks(9950),
                            Gender = 2,
                            Nickname = "韩同学",
                            Password = "A288A447BECB60599F59804FCF69B7770A7F6BC8",
                            Points = 0,
                            Role = 2,
                            Username = "student12"
                        },
                        new
                        {
                            Id = 17,
                            BirthDay = new DateTime(2000, 4, 28, 15, 57, 47, 401, DateTimeKind.Local).AddTicks(9952),
                            Gender = 2,
                            Nickname = "杨同学",
                            Password = "A288A447BECB60599F59804FCF69B7770A7F6BC8",
                            Points = 0,
                            Role = 2,
                            Username = "student13"
                        });
                });

            modelBuilder.Entity("AlgoApp.Data.UserAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Correct")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MyAnswers")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("AlgoApp.Data.Bookmark", b =>
                {
                    b.HasOne("AlgoApp.Data.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoApp.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlgoApp.Data.Classroom", b =>
                {
                    b.HasOne("AlgoApp.Data.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlgoApp.Data.DailyPoints", b =>
                {
                    b.HasOne("AlgoApp.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlgoApp.Data.DailyPractice", b =>
                {
                    b.HasOne("AlgoApp.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlgoApp.Data.FillingAnswer", b =>
                {
                    b.HasOne("AlgoApp.Data.Question", "Question")
                        .WithMany("FillingAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlgoApp.Data.Message", b =>
                {
                    b.HasOne("AlgoApp.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlgoApp.Data.Question", b =>
                {
                    b.HasOne("AlgoApp.Data.Chapter", "Chapter")
                        .WithMany("Questions")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlgoApp.Data.ResultTest", b =>
                {
                    b.HasOne("AlgoApp.Data.Question", "Question")
                        .WithMany("ResultTests")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlgoApp.Data.SelectionOption", b =>
                {
                    b.HasOne("AlgoApp.Data.Question", "Question")
                        .WithMany("SelectionAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlgoApp.Data.StudentToClass", b =>
                {
                    b.HasOne("AlgoApp.Data.Classroom", "Classroom")
                        .WithMany("Students")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoApp.Data.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlgoApp.Data.UserAnswer", b =>
                {
                    b.HasOne("AlgoApp.Data.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoApp.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
